framework:
    default_locale: nb_NO
    session:
        path: '/nb_NO'

account:
    consignor:
        actor_id: 66

consignor:
    shipment_server:
        options:
              actor: 6198
              product_concept_id: 94
              service_id: 9024
              key: PompDeluxNO
              to_address:
                  name: "POMPdeLUX Sverige AB c/o POMPdeLUX"
                  address_line_1: "Møgelhøj 8"
                  postal_code: "8520"
                  city: "Lystrup"
                  country_iso2: DK
                  email: mail@pompdelux.se
                  phone: "+46 8-6117103"

