# DIBS }-------------------------
PaymentBundle_dibs_process:
    pattern:  /payment/dibs/process/{order_id}
    defaults: { _controller: PaymentBundle:Dibs:process }
    requirements:
        order_id:  \d+

PaymentBundle_dibs_callback:
    pattern:  /payment/dibs/callback
    defaults: { _controller: PaymentBundle:Dibs:callback }
    requirements:
        _method: POST

PaymentBundle_dibs_form_update:
    pattern:  /payment/dibs/formupdate
    defaults: { _controller: PaymentBundle:Dibs:block}
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_dibs_cancel:
    pattern:  /payment/dibs/cancel
    defaults: { _controller: PaymentBundle:Default:cancel }

# GOTHIA }-------------------------
PaymentBundle_gothia_payment:
    pattern:  /payment/gothia
    defaults: { _controller: PaymentBundle:Gothia:payment }

PaymentBundle_gothia_process:
    pattern:  /payment/gothia/process
    defaults: { _controller: PaymentBundle:Gothia:process }

PaymentBundle_gothia_payment_test:
    pattern:  /payment/gothia/test
    defaults: { _controller: PaymentBundle:Gothia:test }

PaymentBundle_gothia_payment_checkcustomer:
    pattern:  /payment/gothia/checkcustomer
    defaults: { _controller: PaymentBundle:Gothia:checkCustomer, _format: json }
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_gothia_payment_confirm:
    pattern:  /payment/gothia/confirm
    defaults: { _controller: PaymentBundle:Gothia:confirm, _format: json }
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_gothia_payment_cancel:
    pattern:  /payment/gothia/cancel
    defaults: { _controller: PaymentBundle:Default:cancel }

# GOTHIA DE }-------------------------
PaymentBundle_gothiade_process:
    pattern:  /payment/gothia-de/process
    defaults: { _controller: PaymentBundle:GothiaDE:process }

PaymentBundle_gothiade_payment:
    pattern:  /payment/gothia-de
    defaults: { _controller: PaymentBundle:GothiaDE:payment }

PaymentBundle_gothiade_payment_test:
    pattern:  /payment/gothia-de/test
    defaults: { _controller: PaymentBundle:GothiaDE:test }

PaymentBundle_gothiade_payment_confirm:
    pattern:  /payment/gothia-de/confirm
    defaults: { _controller: PaymentBundle:GothiaDE:confirm, _format: json }
    requirements: { _format: (xml|json), _method: POST }

PaymentBundle_gothiade_payment_cancel:
    pattern:  /payment/gothia-de/cancel
    defaults: { _controller: PaymentBundle:Default:cancel }

# COD }-------------------------
_manualpayment_callback:
    pattern:  /payment/manualpayment/callback
    defaults: { _controller: PaymentBundle:ManualPayment:callback }

# GiftCard }----------------------
_gift_card_callback:
    pattern:  /payment/gift-card/callback
    defaults: { _controller: PaymentBundle:GiftCard:callback }

# Pensio }-------------------------
_pensio_form:
    pattern:  /payment/pensio/form
    defaults:
        _controller: PaymentBundle:Pensio:form
_pensio_wait:
    pattern:  /payment/pensio/wait
    defaults:
        _controller: PaymentBundle:Pensio:wait
_pensio_callback:
    pattern:  /payment/pensio/callback/{status}
    defaults:
        _controller: PaymentBundle:Pensio:callback
        status: failed
    requirements:
        status: (ok|failed)
        _method: POST
_pensio_process:
    pattern:  /payment/pensio/process
    defaults:
        _controller: PaymentBundle:Pensio:process
    requirements:
        _method: POST
_pensio_order_lookup:
    pattern:  /pensio/lookup/order/{order_id}
    defaults:
        _controller: PaymentBundle:Pensio:lookup
    requirements:
        _method: GET


# PayPal }----------------------
_paypal_callback:
    pattern:  /payment/paypal/callback
    defaults: { _controller: PaymentBundle:PayPal:callback }
_paypal_cancel:
    pattern:  /payment/paypal/cancel
    defaults: { _controller: PaymentBundle:PayPal:cancel }


# ALL }-------------------------
_payment_set_method:
    pattern: /checkout/payment/set/method
    defaults:
        _controller: PaymentBundle:Default:setMethod

_process_payment:
    pattern: /checkout/payment/process
    defaults:
        _controller: PaymentBundle:Default:getProcessButton

_payment_cancel:
    pattern:  /payment/cancel
    defaults: { _controller: PaymentBundle:Default:cancel }
