parameters:
    payment.dibsapi.class: Hanzo\Bundle\PaymentBundle\Methods\Dibs\DibsApi
    payment.gothiaapi.class: Hanzo\Bundle\PaymentBundle\Methods\Gothia\GothiaApi
    payment.gothiadeapi.class: Hanzo\Bundle\PaymentBundle\Methods\Gothia\GothiaDEApi
    payment.manualpaymentapi.class: Hanzo\Bundle\PaymentBundle\Methods\ManualPayment\ManualPaymentApi
    payment.giftcard.class: Hanzo\Bundle\PaymentBundle\Methods\GiftCard\GiftCardApi
    payment.pensio.class: Hanzo\Bundle\PaymentBundle\Methods\Pensio\PensioApi
    payment.paypal.class: Hanzo\Bundle\PaymentBundle\Methods\PayPal\PayPalApi

services:
    payment.dibsapi:
        class:           %payment.dibsapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     dibsapi
            parameters:  [@router]
            class:       %payment.dibsapi.class%

    payment.gothiaapi:
        class:           %payment.gothiaapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     gothiaapi
            parameters:  ~
            class:       %payment.gothiaapi.class%

    payment.gothiadeapi:
        class:           %payment.gothiadeapi.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     gothiadeapi
            parameters:  ~
            class:       %payment.gothiadeapi.class%

    payment.manualpaymentapi:
        class:           %payment.manualpaymentapi.class%
        factory_service: service_factory
        factory_method:  get
        scope:           request
        arguments:
            service:     manualpaymentapi
            parameters:  [%kernel.environment%]
            class:       %payment.manualpaymentapi.class%

    payment.giftcardapi:
        class:           %payment.giftcard.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     giftcardapi
            parameters:  ~
            class:       %payment.giftcard.class%

    payment.pensioapi:
        class:           %payment.pensio.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     pensioapi
            parameters:  [@router]
            class:       %payment.pensio.class%

    payment.paypalapi:
        class:           %payment.paypal.class%
        factory_service: service_factory
        factory_method:  get
        arguments:
            service:     paypalapi
            parameters:  [@router, @translator, @logger]
            class:       %payment.paypal.class%
