events_index:
    pattern: /events
    defaults: { _controller: EventsBundle:Events:index }

events_view:
    pattern: /events/{id}
    defaults: { _controller: EventsBundle:Events:view }
    requirements: { id: \d+ }

events_create:
    pattern: /events/create/{id}
    defaults:
        _controller: EventsBundle:Events:create
        id: null
    requirements:
        id: \d+

events_get_feed:
    pattern:  /events/getevents
    defaults:
        _controller: EventsBundle:Events:getEvents
        _format: json
    requirements:
        _format: html|json

events_get_customer:
    pattern:  /events/getcustomer/{email}
    defaults:
        _controller: EventsBundle:Events:getCustomer
        _format: json
    requirements:
        _format: html|json

events_create_customer:
    pattern:  /events/create-customer
    defaults: {  _controller: EventsBundle:Default:createCustomer }

events_fetch_customer:
    pattern:  /events/fetch-customer
    defaults:
        _controller: EventsBundle:Default:fetchCustomer
        _format: json
    requirements:
        _format: html|json

events_delete:
    pattern:  /events/delete/{id}
    defaults:
        _controller: EventsBundle:Events:delete
        _format: json
    requirements:
        _format: html|json
        id: \d+

events_close:
    pattern: /events/close/{id}
    defaults:
        _controller: EventsBundle:Events:close
    requirements:
        _method:  GET
        id: \d+

events_invite:
    pattern: /events/invite/{key}
    defaults:
        _controller: EventsBundle:Events:invite
        key: null

events_remove_participant:
    pattern: /events/remove/participant/{event_id}/{participant_id}
    defaults:
        _controller: EventsBundle:Events:removeParticipant
    requirements:
        event_id: \d+
        participant_id: \d+

events_rsvp:
    pattern: /events/rsvp/{key}
    defaults:
        _controller: EventsBundle:Events:rsvp
        key: null

events_tell_a_friend:
    pattern: /events/tellafriend/{key}
    defaults:
        _controller: EventsBundle:Events:tellAFriend
        key: null

events_sms_rsvp:
    pattern: /events/sms/rsvp
    defaults:
        _controller: EventsBundle:Sms:rsvp
    requirements:
        _method:  GET

events_sms_test:
    pattern: /events/sms/test-123
    defaults:
        _controller: EventsBundle:Sms:sendtest
    requirements:
        _method:  GET

events_set_order_type:
    pattern: /events/set-order-type
    defaults:
        _controller: EventsBundle:Events:setOrderType

events_my_events:
    pattern: /account/my-events
    defaults:
        _controller: EventsBundle:Events:myEvents


advisor_near_you:
    pattern: /events/advisor/near_you/{type}/{latitude}/{longitude}/{showAll}
    defaults:
        _controller: EventsBundle:Advisor:nearYou
        version: v1
        type: 'near'
        latitude: 0.00
        longitude: 0.00
        showAll: 0
    requirements:
        type: '(near|hus)'

advisor_consultants_map_data:
    pattern: /events/advisor/consultants
    defaults:
        _controller: EventsBundle:Advisor:consultants
