login:
    pattern: /login
    defaults:
        _controller: AccountBundle:Security:login

logout:
    pattern: /logout
    defaults:
        _controller: AccountBundle:Security:logout

login_check:
    pattern: /login_check

_account:
    pattern: /account
    defaults:
        _controller: AccountBundle:Default:index

_account_create:
    pattern: /account/create
    defaults:
        _controller: AccountBundle:Default:create

_account_lost_password:
    pattern: /account/password-forgotten
    defaults:
        _controller: AccountBundle:Default:passwordForgotten

_account_history:
    pattern: /account/history/{pager}
    defaults:
        _controller: AccountBundle:History:index
        pager: 1

_account_show_order:
    pattern: /account/order/{order_id}/show
    defaults:
        _controller: AccountBundle:History:view
    requirements:
        order_id: \d+

_account_edit_order:
    pattern: /account/order/{order_id}/edit
    defaults:
        _controller: AccountBundle:History:edit
    requirements:
        order_id: \d+

_account_stop_edit_order:
    pattern: /account/order/{order_id}/stop-edit
    defaults:
        _controller: AccountBundle:Default:stopOrderEdit
    requirements:
        order_id: \d+

_account_delete_order:
    pattern: /account/order/{order_id}/delete
    defaults:
        _controller: AccountBundle:History:delete
    requirements:
        order_id: \d+

_account_edit:
    pattern: /account/edit
    defaults:
        _controller: AccountBundle:Default:edit

_account_edit_address:
    pattern: /account/edit/address/{type}/{shipping_id}
    defaults:
        _controller: AccountBundle:Default:editAddress
        type: ''
        shipping_id: ''

_account_check:
    pattern: /account/check/{type}
    defaults:
        _controller: AccountBundle:Default:check
