Hanzo\Model\Addresses:
    properties:
        first_name:
            - NotBlank:
                message: address.first_name.required
                groups: [shipping, company_shipping, payment, overnightbox]
            - MinLength: 2
        last_name:
            - NotBlank:
                message: address.last_name.required
                groups: [shipping, company_shipping, payment, overnightbox]
            - MinLength: 2
        address_line_1:
            - NotBlank:
                message: address.address_line_1.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - MinLength: 2
            - MaxLength: 35
        postal_code:
            - NotBlank:
                message: address.postal_code.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - MinLength: 2
        city:
            - NotBlank:
                message: address.city.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - MinLength: 2
        countries_id:
            - NotBlank:
                message: address.countries_id.required
                groups: [shipping, company_shipping, payment, overnightbox, customer]
            - Type:
                type: integer
        company_name:
            - NotBlank:
                message: address.company_name.required
                groups: [company_shipping]

Hanzo\Model\Customers:
    properties:
        first_name:
            - NotBlank:
                message: address.first_name.required
                groups: [customer, customer_edit]
            - MinLength:
                limit: 2
                message: address.first_name.min.length
                groups: [customer, customer_edit]
        last_name:
            - NotBlank:
                message: address.last_name.required
                groups: [customer, customer_edit]
            - MinLength:
                limit: 2
                message: address.last_name.min.length
                groups: [customer, customer_edit]
        phone:
            - NotBlank:
                message: phone.required
                groups: [customer, customer_edit]
            - MinLength:
                limit: 8
                message: phone.min.length
                groups: [customer, customer_edit]
            - Regex:
                pattern: "/^\d+$/"
                match:   true
                message: phone.not.valid
                groups: [customer, customer_edit]
        email:
            - NotBlank:
                message: email.required
                groups: [customer, customer_edit]
            - Email:
                message: email.not.valid
                groups: [customer, customer_edit]
        password:
            - NotBlank:
                message: password.required
                groups: [customer]
            - MinLength:
                limit: 5
                message: password.min.length
                groups: [customer]
    # NICETO: figure out why this does not trigger an error
    getters:
        emailUniq:
            - "True":
                message: email.exists
                groups: [customer]
