hanzo_kraken:
    resource: "@HanzoKrakenBundle/Resources/config/routing.xml"
    prefix:   /

stock:
    resource: "@StockBundle/Controller/"
    prefix:   /{_locale}/
    type:     annotation

consignor:
    resource: "@ConsignorBundle/Controller/"
    prefix:   /{_locale}/
    type:     annotation

google:
    resource: "@GoogleBundle/Controller/"
    prefix:   /{_locale}/
    type:     annotation

RetargetingBundle:
    resource: "@RetargetingBundle/Controller/"
    prefix:   /{_locale}/
    type:     annotation
rma:
    resource: "@RMABundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

muneris:
    resource: "@MunerisBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

AxBundle:
    resource: "@AxBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

LocationLocatorBundle:
    resource: "@LocationLocatorBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

DiscountBundle:
    resource: "@DiscountBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

ConsultantNewsletterBundle:
    resource: "@ConsultantNewsletterBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

QuickOrderBundle:
    resource: "@QuickOrderBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

EventsBundle:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

WallBundle:
    resource: "@WallBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

AdminBundle:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

DataIOBundle:
    resource: "@DataIOBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

ShippingBundle:
    resource: "@ShippingBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

ServiceBundle:
    resource: "@ServiceBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

CheckoutBundle:
    resource: "@CheckoutBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

AccountBundle:
    resource: "@AccountBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

NewsletterBundle:
    resource: "@NewsletterBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

PaymentBundle:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

BasketBundle:
    resource: "@BasketBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

SearchBundle:
    resource: "@SearchBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

ProductBundle:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

MannequinBundle:
    resource: "@MannequinBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

CategoryBundle:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

WebServicesBundle:
    resource: "@WebServicesBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

CMSBundle:
    resource: "@CMSBundle/Resources/config/routing.yml"
    prefix:   /{_locale}/

CMSBundle_cms_dyn:
    resource: .
    type: cms

# note we rewrote this to acommodate the locale neded in the start of the url
# _bazinga_exposetranslation:
#     resource: "@BazingaExposeTranslationBundle/Resources/config/routing/routing.yml"
bazinga_exposetranslation_js:
    pattern:  /{_locale}/i18n/{domain_name}.{_format}
    defaults: { _controller: bazinga.exposetranslation.controller:exposeTranslationAction, domain_name: "messages", _format: "js" }
    requirements:
        _format: js

# leverage the template controller in the FrameworkBundle to show static pages:
# @see http://coderwall.com/p/pj1opa
_splash:
    pattern:  /
    defaults:
        _controller: FrameworkBundle:Template:template
        template: CMSBundle:Default:splash.html.twig
        maxAge:       864000
        sharedAge:    864000

liip_theme:
    resource: "@LiipThemeBundle/Resources/config/routing.xml"
    prefix: /{_locale}/theme


# Moved to MunerisBundle
# NnoBundle:
#     resource: "@NnoBundle/Resources/config/routing.yml"
#     prefix:   /{_locale}/



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
