cms:
    frontpage: 538

framework:
    default_locale: de_AT
    session:
        cookie_path: '/de_AT'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_at_database_user%
                password:             %prod_at_database_password%
                dsn:                  mysql:host=%prod_at_database_host%;dbname=%prod_at_database_name%
                options:              {}
                attributes:           {}

consignor:
    shipment_server: ~

google:
    site_verification:
        - "idm5dDOLlFrLJl2npZ8fgvE3j0a_OlYPK3O-j37DxLI"
        - "XQd3QHxI9Xa9d5d-ExR5LZEz6JO9--7l1d9LAhwnGcg" # Heinrich
        - "SBOj-_vTXS3T6HczLxCmAwi-cAn5h1OrIuz_c5DmK8M" # Katrine
    tag_manager:
        gtm_id: "GTM-5Z5LLV"
        enabled_datalayers:
            - Ecommerce
