framework:
    default_locale: en_GB
    session:
        cookie_path: '/en_GB'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_dk_database_user%
                password:             %prod_dk_database_password%
                dsn:                  mysql:host=%prod_dk_database_host%;dbname=%prod_dk_database_name%
                options:              {}
                attributes:           {}
                slaves:
                    pdldbdk2:
                        user:         %prod_dk_database_slave_1_user%
                        password:     %prod_dk_database_slave_1_password%
                        dsn:          %prod_dk_database_slave_1_dsn%
                    # pdldbdk3:
                    #     user:         %prod_dk_database_slave_2_user%
                    #     password:     %prod_dk_database_slave_2_password%
                    #     dsn:          %prod_dk_database_slave_2_dsn%
                    # pdldbdk4:
                    #     user:         %prod_dk_database_slave_3_user%
                    #     password:     %prod_dk_database_slave_3_password%
                    #     dsn:          %prod_dk_database_slave_3_dsn%

account:
    consignor:
        actor_id: 63
