framework:
    default_locale: da_DK
    session:
        cookie_path: '/da_DK'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_dk_database_user%
                password:             %prod_dk_database_password%
                dsn:                  mysql:host=%prod_dk_database_host%;dbname=%prod_dk_database_name%
                options:              {}
                attributes:           {}
                slaves:
                    pdldbdk2:
                        user:         %prod_dk_database_slave_1_user%
                        password:     %prod_dk_database_slave_1_password%
                        dsn:          %prod_dk_database_slave_1_dsn%
                    # pdldbdk3:
                    #     user:         %prod_dk_database_slave_2_user%
                    #     password:     %prod_dk_database_slave_2_password%
                    #     dsn:          %prod_dk_database_slave_2_dsn%
                    # pdldbdk4:
                    #     user:         %prod_dk_database_slave_3_user%
                    #     password:     %prod_dk_database_slave_3_password%
                    #     dsn:          %prod_dk_database_slave_3_dsn%
            pdldbde1:
                driver:               %database_driver%
                user:                 %prod_de_database_user%
                password:             %prod_de_database_password%
                dsn:                  mysql:host=%prod_de_database_host%;dbname=%prod_de_database_name%
                options:              {}
                attributes:           {}
            pdldbfi1:
                driver:               %database_driver%
                user:                 %prod_fi_database_user%
                password:             %prod_fi_database_password%
                dsn:                  mysql:host=%prod_fi_database_host%;dbname=%prod_fi_database_name%
                options:              {}
                attributes:           {}
            pdldbnl1:
                driver:               %database_driver%
                user:                 %prod_nl_database_user%
                password:             %prod_nl_database_password%
                dsn:                  mysql:host=%prod_nl_database_host%;dbname=%prod_nl_database_name%
                options:              {}
                attributes:           {}
            pdldbno1:
                driver:               %database_driver%
                user:                 %prod_no_database_user%
                password:             %prod_no_database_password%
                dsn:                  mysql:host=%prod_no_database_host%;dbname=%prod_no_database_name%
                options:              {}
                attributes:           {}
            pdldbse1:
                driver:               %database_driver%
                user:                 %prod_se_database_user%
                password:             %prod_se_database_password%
                dsn:                  mysql:host=%prod_se_database_host%;dbname=%prod_se_database_name%
                options:              {}
                attributes:           {}
            pdldbat1:
                driver:               %database_driver%
                user:                 %prod_at_database_user%
                password:             %prod_at_database_password%
                dsn:                  mysql:host=%prod_at_database_host%;dbname=%prod_at_database_name%
                options:              {}
                attributes:           {}
            pdldbch1:
                driver:               %database_driver%
                user:                 %prod_ch_database_user%
                password:             %prod_ch_database_password%
                dsn:                  mysql:host=%prod_ch_database_host%;dbname=%prod_ch_database_name%
                options:              {}
                attributes:           {}
