framework:
    default_locale: da_DK
    session:
        cookie_path: '/da_DK'

propel:
    dbal:
        default_connection: pdldbdk1
        connections:
            pdldbdk1:
                driver:               %database_driver%
                user:                 %prod_dk_database_user%
                password:             %prod_dk_database_password%
                dsn:                  mysql:host=%prod_dk_database_host%;dbname=%prod_dk_database_name%
                options:              {}
                attributes:           {}
# ------------------------------------------------------------------------------------------
# we no longer use slaves, if we ever need to again - this is the block to enable/duplicate
# ------------------------------------------------------------------------------------------
#                slaves:
#                    pdldbdk2:
#                        user:         %prod_dk_database_slave_1_user%
#                        password:     %prod_dk_database_slave_1_password%
#                        dsn:          %prod_dk_database_slave_1_dsn%
# ------------------------------------------------------------------------------------------
            pdldbde1:
                driver:               %database_driver%
                user:                 %prod_de_database_user%
                password:             %prod_de_database_password%
                dsn:                  mysql:host=%prod_de_database_host%;dbname=%prod_de_database_name%
                options:              {}
                attributes:           {}
            pdldbfi1:
                driver:               %database_driver%
                user:                 %prod_fi_database_user%
                password:             %prod_fi_database_password%
                dsn:                  mysql:host=%prod_fi_database_host%;dbname=%prod_fi_database_name%
                options:              {}
                attributes:           {}
            pdldbnl1:
                driver:               %database_driver%
                user:                 %prod_nl_database_user%
                password:             %prod_nl_database_password%
                dsn:                  mysql:host=%prod_nl_database_host%;dbname=%prod_nl_database_name%
                options:              {}
                attributes:           {}
            pdldbno1:
                driver:               %database_driver%
                user:                 %prod_no_database_user%
                password:             %prod_no_database_password%
                dsn:                  mysql:host=%prod_no_database_host%;dbname=%prod_no_database_name%
                options:              {}
                attributes:           {}
            pdldbse1:
                driver:               %database_driver%
                user:                 %prod_se_database_user%
                password:             %prod_se_database_password%
                dsn:                  mysql:host=%prod_se_database_host%;dbname=%prod_se_database_name%
                options:              {}
                attributes:           {}
            pdldbat1:
                driver:               %database_driver%
                user:                 %prod_at_database_user%
                password:             %prod_at_database_password%
                dsn:                  mysql:host=%prod_at_database_host%;dbname=%prod_at_database_name%
                options:              {}
                attributes:           {}
            pdldbch1:
                driver:               %database_driver%
                user:                 %prod_ch_database_user%
                password:             %prod_ch_database_password%
                dsn:                  mysql:host=%prod_ch_database_host%;dbname=%prod_ch_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 63

consignor:
    shipment_server:
        options:
            actor: 146
            product_concept_id: 94
            service_id: ""
            key: PompDeluxDK
            to_address:
                name: "POMPdeLUX ApS"
                address_line_1: "Grydh√∏jparken 10"
                postal_code: "8381"
                city: "Tilst"
                country_iso2: DK
                email: mail@pompdelux.dk
                phone: "+45 8678 7871"

google:
    site_verification:
        - "UofA3REZ5SFYNzo-zNzIHkhOUDo3qblDAQadaNRk_2s"
        - "V6U4jsJtOJKEOK7J3Hkw9mTz344Yb7FYsNpjbCm3dQg"
        - "wLHjgqyCGImP2YG1fA_y_rggXUwLHJ1M0ym2Omxj95Q" # katrine
    tag_manager:
        gtm_id:             "GTM-NKC8X3"
        enabled_datalayers:
            - Ecommerce
            - Remarketing
        analytics_code:     ~
        addwords:
            conversion_id: 976104979
            conversion_label: VxRuCK2O_goQk9y40QM
