cms:
    frontpage: 540

framework:
    default_locale: sv_SE
    session:
        cookie_path: '/sv_SE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_se_database_user%
                password:             %prod_se_database_password%
                dsn:                  mysql:host=%prod_se_database_host%;dbname=%prod_se_database_name%
                options:              {}
                attributes:           {}

account:
    consignor:
        actor_id: 64

consignor:
    shipment_server:
        options:
              actor: 143
              product_concept_id: 882
              service_id: ""
              key: PompDeluxSE
              to_address:
                  name: "POMPdeLUX Sverige AB c/o POMPdeLUX"
                  address_line_1: "Grydh√∏jparken 10"
                  postal_code: "8381"
                  city: "Tilst"
                  country_iso2: DK
                  email: mail@pompdelux.se
                  phone: "+46 8-6117103"

google:
    analytics_code:    UA-1793665-3
    conversion_id:     976104979
    site_verification: "i-GTUV7HLYYWlH1qe3eO9rSythi037P722GF5w4zk_w"
