cms:
    frontpage: 540

framework:
    default_locale: sv_SE
    session:
        cookie_path: '/sv_SE'

propel:
    dbal:
        default_connection: default
        connections:
            default:
                driver:               %database_driver%
                user:                 %prod_se_database_user%
                password:             %prod_se_database_password%
                dsn:                  mysql:host=%prod_se_database_host%;dbname=%prod_se_database_name%
                options:              {}
                attributes:           {}
                # slaves:
                #     pdldbdk2:
                #         user:         %database_slave_1_user%
                #         password:     %database_slave_1_password%
                #         dsn:          %database_slave_1_dsn%
                #     pdldbdk3:
                #         user:         %database_slave_2_user%
                #         password:     %database_slave_2_password%
                #         dsn:          %database_slave_2_dsn%
                #     pdldbdk4:
                #         user:         %database_slave_3_user%
                #         password:     %database_slave_3_password%
                #         dsn:          %database_slave_3_dsn%

account:
    consignor:
        actor_id: 64
