product_info:
    pattern:    /product/view/{product_id}
    defaults:
        _controller: ProductBundle:Default:view
        product_id: 1
    requirements:
        product_id: \d+

product_set:
    pattern:    /product/bundle/{image_id}/{return}
    defaults:
        _controller: ProductBundle:Bundle:view
        image_id: 1
    requirements:
        image_id: \d+

product_custom_set:
    pattern:    /product/bundle/set/{set}
    defaults:
        _controller: ProductBundle:Bundle:custom
        set: 1

product_set_active_range:
    pattern: /set/active/product/range
    defaults:
        _controller: ProductBundle:Range:setRange
